name: Setup
description: Install Bun, Just, and project dependencies

inputs:
  npm-token:
    description: Token for authenticating against npm.pkg.github.com
    required: true

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
      with:
        bun-version-file: ".bun-version"

    - uses: taiki-e/install-action@fd0f63e180a477d7434580b6d80817978b9ff2b8 # v2.70.1
      with:
        tool: just

    - name: Install deps
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.npm-token }}
      run: bun i --frozen-lockfile
