name: Yarn Cache
description: Installs dependencies and caches node_modules and yarn's cache
runs:
  using: "composite"
  steps:
    - name: Output Yarn cache directory
      id: yarn-cache-dir-path
      shell: "bash"
      run: |
        echo "out=$(yarn cache dir)" >> $GITHUB_OUTPUT
    - name: Cache Yarn
      id: cache-yarn
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          ${{ steps.yarn-cache-dir-path.outputs.out }}
        key: "${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}"
    - name: Install dependencies
      if: steps.cache-yarn.outputs.cache-hit != 'true'
      shell: "bash"
      run: |
        yarn install --prefer-offline --frozen-lockfile
