name: CI

on:
  pull_request:
    branches:
      - master

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  run-check:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"

      - uses: taiki-e/install-action@a164de717a0ee9284c2d9db1c6016a4c339cd333 # v2.69.14
        with:
          tool: just

      - name: Install deps
        run: bun i --frozen-lockfile

      - name: Format check
        run: just format-check

      - name: Lint
        run: just lint

      - name: Typecheck
        run: just typecheck

      - name: Test
        run: just test

      - name: Check Translations
        run: just check-translations
