name: CI

on:
  pull_request:
    branches:
      - master

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  run-check:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup

      - name: Format check
        run: just format-check

      - name: Lint
        run: just lint

      - name: Typecheck
        run: just typecheck

      - name: Test
        run: just test

      - name: Check Translations
        run: just check-translations
