name: CI

on:
  pull_request:
    branches:
      - master

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Format check
        run: just format-check

      - name: Lint
        run: just lint

      - name: Typecheck
        run: just typecheck

      - name: Test
        run: just test

      - name: Check Translations
        run: just check-translations
